/**
 * data.js — Données statiques Collectioner
 * Inclure dans chaque page : <script src="data.js"></script>
 */

/* ══════════════════════════════════════════════════════
   SCREENSCRAPER — Map console → systemeid
══════════════════════════════════════════════════════ */
var SS_SYSTEMS = {
    'NES':               3,  'Famicom':           3,
    'SNES':              4,  'Super Famicom':      4,
    'Nintendo 64':       14, 'N64':                14,
    'GameCube':          13, 'Wii':                36,
    'Wii U':             18, 'Switch':             225,
    'Game Boy':          9,  'GB':                 9,
    'Game Boy Color':    10, 'GBC':                10,
    'Game Boy Advance':  12, 'GBA':                12,
    'Nintendo DS':       15, 'NDS':                15,
    'Nintendo 3DS':      17, '3DS':                17,
    'PS1':               57, 'PlayStation':        57,
    'PS2':               58, 'PlayStation 2':      58,
    'PS3':               59, 'PlayStation 3':      59,
    'PS4':               60, 'PlayStation 4':      60,
    'PS5':               227,'PlayStation 5':      227,
    'PSP':               61, 'PS Vita':            62,
    'Xbox':              32, 'Xbox 360':           33,
    'Xbox One':          34, 'Xbox Series':        220,
    'Mega Drive':        1,  'Genesis':            1,
    'Master System':     2,  'Game Gear':          21,
    'Saturn':            22, 'Dreamcast':          23,
    'Atari 2600':        26, 'Atari 7800':         41,
    'Atari Jaguar':      29, 'Lynx':               28,
    'Neo Geo':           142,'Neo Geo Pocket':     25,
    'PC Engine':         31, 'TurboGrafx-16':      31,
    'Amiga':             64, 'DOS':                135,
    'PC':                135,'Windows':            135,
};

/* ══════════════════════════════════════════════════════
   TEMPLATES CONSOLES
══════════════════════════════════════════════════════ */
var CONSOLE_TEMPLATES = [
    // ── NINTENDO SALON ──
    { nom:'NES',                        marque:'Nintendo', region:'PAL (Europe)',  modele:'NES-001 FAT' },
    { nom:'NES',                        marque:'Nintendo', region:'PAL (Europe)',  modele:'NES-101 Top Loader' },
    { nom:'NES Mini (officielle)',       marque:'Nintendo', region:'PAL (Europe)',  modele:'CLV-301' },
    { nom:'NES Mini (clone chinois)',    marque:'',         region:'PAL (Europe)',  modele:'Clone' },
    { nom:'SNES',                       marque:'Nintendo', region:'PAL (Europe)',  modele:'FAT SNSP-001' },
    { nom:'SNES Mini (officielle)',      marque:'Nintendo', region:'PAL (Europe)',  modele:'SNSP-098' },
    { nom:'Super Famicom',              marque:'Nintendo', region:'NTSC-J (Japon)',modele:'SHVC-001' },
    { nom:'Nintendo 64',                marque:'Nintendo', region:'PAL (Europe)',  modele:'NUS-001' },
    { nom:'GameCube',                   marque:'Nintendo', region:'PAL (Europe)',  modele:'DOL-001' },
    { nom:'Wii',                        marque:'Nintendo', region:'PAL (Europe)',  modele:'FAT RVL-001' },
    { nom:'Wii Mini',                   marque:'Nintendo', region:'PAL (Europe)',  modele:'RVL-201' },
    { nom:'Wii U',                      marque:'Nintendo', region:'PAL (Europe)',  modele:'WUP-101' },
    { nom:'Switch',                     marque:'Nintendo', region:'PAL (Europe)',  modele:'HAC-001 V1' },
    { nom:'Switch',                     marque:'Nintendo', region:'PAL (Europe)',  modele:'HAC-001(-01) V2' },
    { nom:'Switch Lite',                marque:'Nintendo', region:'PAL (Europe)',  modele:'HDH-001' },
    { nom:'Switch OLED',                marque:'Nintendo', region:'PAL (Europe)',  modele:'HEG-001' },
    // ── NINTENDO PORTABLE ──
    { nom:'Game Boy',                   marque:'Nintendo', region:'PAL (Europe)',  modele:'DMG-001' },
    { nom:'Game Boy Pocket',            marque:'Nintendo', region:'PAL (Europe)',  modele:'MGB-001' },
    { nom:'Game Boy Color',             marque:'Nintendo', region:'PAL (Europe)',  modele:'CGB-001' },
    { nom:'Game Boy Advance',           marque:'Nintendo', region:'PAL (Europe)',  modele:'AGB-001' },
    { nom:'Game Boy Advance SP',        marque:'Nintendo', region:'PAL (Europe)',  modele:'AGS-001' },
    { nom:'Game Boy Micro',             marque:'Nintendo', region:'PAL (Europe)',  modele:'OXY-001' },
    { nom:'Nintendo DS',                marque:'Nintendo', region:'PAL (Europe)',  modele:'FAT NTR-001' },
    { nom:'Nintendo DS Lite',           marque:'Nintendo', region:'PAL (Europe)',  modele:'USG-001' },
    { nom:'Nintendo DSi',               marque:'Nintendo', region:'PAL (Europe)',  modele:'TWL-001' },
    { nom:'Nintendo DSi XL',            marque:'Nintendo', region:'PAL (Europe)',  modele:'UTL-001' },
    { nom:'Nintendo 3DS',               marque:'Nintendo', region:'PAL (Europe)',  modele:'CTR-001' },
    { nom:'Nintendo 3DS XL',            marque:'Nintendo', region:'PAL (Europe)',  modele:'SPR-001' },
    { nom:'Nintendo 2DS',               marque:'Nintendo', region:'PAL (Europe)',  modele:'FTR-001' },
    { nom:'New Nintendo 3DS',           marque:'Nintendo', region:'PAL (Europe)',  modele:'KTR-001' },
    { nom:'New Nintendo 3DS XL',        marque:'Nintendo', region:'PAL (Europe)',  modele:'RED-001' },
    { nom:'New Nintendo 2DS XL',        marque:'Nintendo', region:'PAL (Europe)',  modele:'JAN-001' },
    // ── SEGA SALON ──
    { nom:'Master System',              marque:'Sega',     region:'PAL (Europe)',  modele:'Mark III FAT' },
    { nom:'Master System II',           marque:'Sega',     region:'PAL (Europe)',  modele:'Master System II' },
    { nom:'Mega Drive',                 marque:'Sega',     region:'PAL (Europe)',  modele:'FAT MK-1601' },
    { nom:'Mega Drive II',              marque:'Sega',     region:'PAL (Europe)',  modele:'FAT MK-1631' },
    { nom:'Mega Drive Mini',            marque:'Sega',     region:'PAL (Europe)',  modele:'Mini HAA-2521' },
    { nom:'Mega Drive AtGames Flashback HD', marque:'AtGames', region:'PAL (Europe)', modele:'AtGames' },
    { nom:'Mega Drive Arcade Legends',  marque:'AtGames', region:'PAL (Europe)',  modele:'Arcade Legends' },
    { nom:'Mega-CD',                    marque:'Sega',     region:'PAL (Europe)',  modele:'MK-4102 MCD I' },
    { nom:'Mega-CD II',                 marque:'Sega',     region:'PAL (Europe)',  modele:'MK-4121 MCD II' },
    { nom:'32X',                        marque:'Sega',     region:'PAL (Europe)',  modele:'MK-84000' },
    { nom:'Saturn',                     marque:'Sega',     region:'PAL (Europe)',  modele:'FAT MK-80200' },
    { nom:'Saturn',                     marque:'Sega',     region:'PAL (Europe)',  modele:'SLIM MK-80200A' },
    { nom:'Dreamcast',                  marque:'Sega',     region:'PAL (Europe)',  modele:'HKT-3030' },
    { nom:'Console Flashback',          marque:'AtGames', region:'PAL (Europe)',  modele:'Flashback' },
    // ── SEGA PORTABLE ──
    { nom:'Game Gear',                  marque:'Sega',     region:'PAL (Europe)',  modele:'HGG-3210' },
    // ── SONY ──
    { nom:'PlayStation 1',              marque:'Sony',     region:'PAL (Europe)',  modele:'FAT SCPH-1002' },
    { nom:'PlayStation 1',              marque:'Sony',     region:'PAL (Europe)',  modele:'FAT SCPH-5502' },
    { nom:'PSone',                      marque:'Sony',     region:'PAL (Europe)',  modele:'SLIM SCPH-102' },
    { nom:'PlayStation 1',              marque:'Sony',     region:'NTSC-J (Japon)',modele:'FAT SCPH-1000' },
    { nom:'PlayStation 2',              marque:'Sony',     region:'PAL (Europe)',  modele:'FAT SCPH-30004' },
    { nom:'PlayStation 2',              marque:'Sony',     region:'PAL (Europe)',  modele:'SLIM SCPH-77004' },
    { nom:'PlayStation 3',              marque:'Sony',     region:'PAL (Europe)',  modele:'FAT CECHC04' },
    { nom:'PlayStation 3',              marque:'Sony',     region:'PAL (Europe)',  modele:'SLIM CECH-2504A' },
    { nom:'PlayStation 3',              marque:'Sony',     region:'PAL (Europe)',  modele:'Super SLIM CECH-4304A' },
    { nom:'PlayStation 4',              marque:'Sony',     region:'PAL (Europe)',  modele:'FAT CUH-1216A' },
    { nom:'PlayStation 4 Slim',         marque:'Sony',     region:'PAL (Europe)',  modele:'SLIM CUH-2216A' },
    { nom:'PlayStation 4 Pro',          marque:'Sony',     region:'PAL (Europe)',  modele:'Pro CUH-7216B' },
    { nom:'PlayStation 5',              marque:'Sony',     region:'PAL (Europe)',  modele:'FAT CFI-1016A' },
    { nom:'PlayStation 5 Slim',         marque:'Sony',     region:'PAL (Europe)',  modele:'SLIM CFI-2016A' },
    { nom:'PSP',                        marque:'Sony',     region:'PAL (Europe)',  modele:'PSP-1004 FAT' },
    { nom:'PSP',                        marque:'Sony',     region:'PAL (Europe)',  modele:'PSP-2004 Slim' },
    { nom:'PSP',                        marque:'Sony',     region:'PAL (Europe)',  modele:'PSP-3004 Brite' },
    { nom:'PSP Go',                     marque:'Sony',     region:'PAL (Europe)',  modele:'PSP-N1004' },
    { nom:'PS Vita',                    marque:'Sony',     region:'PAL (Europe)',  modele:'FAT PCH-1104' },
    { nom:'PS Vita Slim',               marque:'Sony',     region:'PAL (Europe)',  modele:'SLIM PCH-2004' },
    // ── MICROSOFT ──
    { nom:'Xbox',                       marque:'Microsoft',region:'PAL (Europe)',  modele:'FAT' },
    { nom:'Xbox 360',                   marque:'Microsoft',region:'PAL (Europe)',  modele:'FAT' },
    { nom:'Xbox 360',                   marque:'Microsoft',region:'PAL (Europe)',  modele:'SLIM S' },
    { nom:'Xbox 360',                   marque:'Microsoft',region:'PAL (Europe)',  modele:'SLIM E' },
    { nom:'Xbox One',                   marque:'Microsoft',region:'PAL (Europe)',  modele:'FAT' },
    { nom:'Xbox One S',                 marque:'Microsoft',region:'PAL (Europe)',  modele:'SLIM' },
    { nom:'Xbox One X',                 marque:'Microsoft',region:'PAL (Europe)',  modele:'X' },
    { nom:'Xbox Series S',              marque:'Microsoft',region:'PAL (Europe)',  modele:'Series S' },
    { nom:'Xbox Series X',              marque:'Microsoft',region:'PAL (Europe)',  modele:'Series X' },
    // ── ATARI ──
    { nom:'Atari 2600',                 marque:'Atari',    region:'PAL (Europe)',  modele:'FAT' },
    { nom:'Atari 2600 Junior',          marque:'Atari',    region:'PAL (Europe)',  modele:'Junior' },
    { nom:'Atari 7800',                 marque:'Atari',    region:'PAL (Europe)',  modele:'7800' },
    { nom:'Atari Jaguar',               marque:'Atari',    region:'PAL (Europe)',  modele:'Jaguar' },
    { nom:'Atari Lynx',                 marque:'Atari',    region:'PAL (Europe)',  modele:'Lynx I' },
    { nom:'Atari Lynx II',              marque:'Atari',    region:'PAL (Europe)',  modele:'Lynx II' },
];

/* ══════════════════════════════════════════════════════
   TEMPLATES ACCESSOIRES
══════════════════════════════════════════════════════ */
var TEMPLATES = {
    manette: [
        // Nintendo NES
        { nom:'Manette NES',                        console:'NES',              marque:'Nintendo' },
        { nom:'Manette NES Advantage',              console:'NES',              marque:'Nintendo' },
        { nom:'Manette NES Max',                    console:'NES',              marque:'Nintendo' },
        { nom:'NES Four Score (Multitap)',           console:'NES',              marque:'Nintendo' },
        { nom:'Arcade Stick NES',                   console:'NES',              marque:'' },
        { nom:'Manette NES non officielle',         console:'NES',              marque:'' },
        // Nintendo SNES / Super Famicom
        { nom:'Manette SNES',                       console:'SNES',             marque:'Nintendo' },
        { nom:'Manette Super Famicom',              console:'SNES',             marque:'Nintendo' },
        { nom:'SNES Multitap',                      console:'SNES',             marque:'Nintendo' },
        { nom:'SNES Mouse',                         console:'SNES',             marque:'Nintendo' },
        { nom:'Manette SNES Hori',                  console:'SNES',             marque:'Hori' },
        { nom:'Arcade Stick SNES PAL',              console:'SNES',             marque:'' },
        { nom:'Arcade Stick Super Famicom (JAP)',   console:'SNES',             marque:'' },
        { nom:'Manette ASCII SNES',                 console:'SNES',             marque:'ASCII' },
        { nom:'Manette SNES non officielle',        console:'SNES',             marque:'' },
        // Nintendo 64
        { nom:'Manette Nintendo 64',                console:'Nintendo 64',      marque:'Nintendo' },
        { nom:'Manette N64 Hori Mini',              console:'Nintendo 64',      marque:'Hori' },
        { nom:'Manette N64 non officielle',         console:'Nintendo 64',      marque:'' },
        // GameCube
        { nom:'Manette GameCube',                   console:'GameCube',         marque:'Nintendo' },
        { nom:'Manette GameCube Wavebird',          console:'GameCube',         marque:'Nintendo',  notes:'Manette sans fil officielle Nintendo' },
        { nom:'Manette GameCube Hori',              console:'GameCube',         marque:'Hori' },
        // Wii
        { nom:'Wiimote',                            console:'Wii',              marque:'Nintendo' },
        { nom:'Nunchuk',                            console:'Wii',              marque:'Nintendo' },
        { nom:'Manette Wii Classic',                console:'Wii',              marque:'Nintendo' },
        { nom:'Manette Wii Classic Pro',            console:'Wii',              marque:'Nintendo' },
        // Wii U / Switch
        { nom:'Manette Wii U Pro',                  console:'Wii U',            marque:'Nintendo' },
        { nom:'Joy-Con (L)',                        console:'Switch',           marque:'Nintendo' },
        { nom:'Joy-Con (R)',                        console:'Switch',           marque:'Nintendo' },
        { nom:'Manette Switch Pro',                 console:'Switch',           marque:'Nintendo' },
        // Sega Master System
        { nom:'Manette Master System',              console:'Master System',    marque:'Sega' },
        { nom:'Arcade Stick Master System',         console:'Master System',    marque:'' },
        { nom:'Manette Master System Retrobit',     console:'Master System',    marque:'Retrobit' },
        { nom:'Manette Master System non officielle', console:'Master System',  marque:'' },
        // Sega Mega Drive
        { nom:'Manette Mega Drive 3 boutons',       console:'Mega Drive',       marque:'Sega' },
        { nom:'Manette Mega Drive 6 boutons',       console:'Mega Drive',       marque:'Sega' },
        { nom:'Manette Mega Drive 3 boutons PAL',   console:'Mega Drive',       marque:'Sega' },
        { nom:'Arcade Stick Mega Drive PAL',        console:'Mega Drive',       marque:'' },
        { nom:'Arcade Stick Mega Drive JAP/US',     console:'Mega Drive',       marque:'' },
        { nom:'Manette Mega Drive non officielle',  console:'Mega Drive',       marque:'' },
        { nom:'Manette Mega Drive Retrobit',        console:'Mega Drive',       marque:'Retrobit' },
        { nom:'Manette Mega Drive Mini',            console:'Mega Drive',       marque:'Sega',      notes:'Manette livrée avec la Mega Drive Mini' },
        // Sega Saturn / Dreamcast / 32X
        { nom:'Manette Saturn',                     console:'Saturn',           marque:'Sega' },
        { nom:'Manette Saturn 3D',                  console:'Saturn',           marque:'Sega' },
        { nom:'Arcade Stick Saturn',                console:'Saturn',           marque:'' },
        { nom:'Manette Dreamcast',                  console:'Dreamcast',        marque:'Sega' },
        { nom:'Arcade Stick Dreamcast',             console:'Dreamcast',        marque:'' },
        { nom:'Manette 32X',                        console:'32X',              marque:'Sega' },
        // Sony PlayStation
        { nom:'Manette PS1',                        console:'PS1',              marque:'Sony' },
        { nom:'DualShock',                          console:'PS1',              marque:'Sony' },
        { nom:'DualShock 2',                        console:'PS2',              marque:'Sony' },
        { nom:'DualShock 3',                        console:'PS3',              marque:'Sony' },
        { nom:'DualShock 4',                        console:'PS4',              marque:'Sony' },
        { nom:'DualSense',                          console:'PS5',              marque:'Sony' },
        { nom:'Manette PS1 Hori',                   console:'PS1',              marque:'Hori' },
        { nom:'Manette PS2 Hori',                   console:'PS2',              marque:'Hori' },
        { nom:'Arcade Stick PS1',                   console:'PS1',              marque:'' },
        { nom:'Arcade Stick PS2',                   console:'PS2',              marque:'' },
        // Microsoft Xbox
        { nom:'Manette Xbox',                       console:'Xbox',             marque:'Microsoft' },
        { nom:'Manette Xbox 360',                   console:'Xbox 360',         marque:'Microsoft' },
        { nom:'Manette Xbox One',                   console:'Xbox One',         marque:'Microsoft' },
        // Atari
        { nom:'Joystick Atari 2600',                console:'Atari 2600',       marque:'Atari' },
        { nom:'Paddle Atari 2600',                  console:'Atari 2600',       marque:'Atari' },
        { nom:'Manette Atari 7800',                 console:'Atari 7800',       marque:'Atari' },
        { nom:'Manette Atari Jaguar',               console:'Atari Jaguar',     marque:'Atari' },
        { nom:'Manette Atari Jaguar Pro',           console:'Atari Jaguar',     marque:'Atari' },
        { nom:'Manette Atari Lynx',                 console:'Atari Lynx',       marque:'Atari' },
        { nom:'Joystick Atari ST',                  console:'Atari ST',         marque:'Atari' },
        // Générique
        { nom:'Arcade Stick générique',             console:'',                 marque:'' },
        { nom:'Manette non officielle',             console:'',                 marque:'' },
    ],
    cable: [
        { nom:'Câble Péritel',                      console:'',     notes:'Câble vidéo composite via prise Péritel (SCART)' },
        { nom:'Câble RGB SCART',                    console:'',     notes:'Câble RGB via prise Péritel — meilleure qualité image analogique' },
        { nom:'Câble Composite',                    console:'',     notes:'Câble vidéo composite (prise jaune + audio rouge/blanc)' },
        { nom:'Câble S-Video',                      console:'',     notes:'Câble S-Video — meilleure qualité que composite' },
        { nom:'Câble Component YPbPr',              console:'',     notes:'Câble composantes (rouge/vert/bleu) — qualité HD analogique' },
        { nom:'Câble HDMI',                         console:'',     notes:'' },
        { nom:'Câble RF / Antenne',                 console:'',     notes:'Câble RF pour connexion TV via prise antenne (canal 3/4)' },
        { nom:'Câble Alimentation',                 console:'',     notes:'' },
        { nom:'Alimentation US (import)',           console:'',     notes:'Adaptateur secteur pour consoles import NTSC-U' },
        { nom:'Câble USB',                          console:'',     notes:'' },
        { nom:'Link Cable Game Boy',                console:'Game Boy', notes:'Câble de liaison pour jeu multijoueur local' },
        { nom:'Câble Audio Stéréo RCA',             console:'',     notes:'Câble audio rouge/blanc' },
        { nom:'Câble Extension Manette',            console:'',     notes:'' },
    ],
    adaptateur: [
        { nom:'Adaptateur secteur Game Gear',       console:'Game Gear',        notes:'Alimentation secteur pour Game Gear (évite les piles)' },
        { nom:'Adaptateur Manette NES → USB',       console:'NES',              notes:"Permet d'utiliser une manette NES sur PC/Raspberry" },
        { nom:'Adaptateur Manette SNES → USB',      console:'SNES',             notes:'' },
        { nom:'Adaptateur Manette N64 → USB',       console:'Nintendo 64',      notes:'' },
        { nom:'Adaptateur Manette GC → Wii U',      console:'GameCube',         notes:'Adaptateur officiel Nintendo' },
        { nom:'Adaptateur Manette GC → Switch',     console:'GameCube',         notes:'' },
        { nom:'Adaptateur Manette PS1/PS2 → USB',   console:'PS1',              notes:'' },
        { nom:'Adaptateur SCART → HDMI',            console:'',                 notes:'Convertisseur SCART vers HDMI' },
        { nom:'Adaptateur RGB → HDMI',              console:'',                 notes:'Upscaler RGB vers HDMI' },
        { nom:'Adaptateur Péritel → RCA',           console:'',                 notes:'' },
        { nom:'Adaptateur secteur EU → US',         console:'',                 notes:'Adaptateur pour alimentation import' },
        { nom:'Adaptateur Memory Card',             console:'',                 notes:'' },
    ],
    peripherique: [
        { nom:'Pistolet Zapper',                    console:'NES',              marque:'Nintendo' },
        { nom:'Power Pad',                          console:'NES',              marque:'Nintendo' },
        { nom:'R.O.B.',                             console:'NES',              marque:'Nintendo' },
        { nom:'NES Advantage',                      console:'NES',              marque:'Nintendo' },
        { nom:'Super Scope',                        console:'SNES',             marque:'Nintendo' },
        { nom:'Konami Justifier',                   console:'SNES',             marque:'Konami' },
        { nom:'Nintendo 64 Transfer Pak',           console:'Nintendo 64',      marque:'Nintendo' },
        { nom:'Game Boy Player',                    console:'GameCube',         marque:'Nintendo' },
        { nom:'Balance Board',                      console:'Wii',              marque:'Nintendo' },
        { nom:'Wii MotionPlus',                     console:'Wii',              marque:'Nintendo' },
        { nom:'GunCon',                             console:'PS1',              marque:'Namco' },
        { nom:'GunCon 2',                           console:'PS2',              marque:'Namco' },
        { nom:'Guitar Hero Guitare',                console:'',                 marque:'' },
        { nom:'Dance Pad',                          console:'',                 marque:'' },
        { nom:'Volant',                             console:'',                 marque:'' },
        { nom:'Memory Card PS1',                    console:'PS1',              marque:'Sony' },
        { nom:'Memory Card PS2',                    console:'PS2',              marque:'Sony' },
        { nom:'Memory Card GameCube',               console:'GameCube',         marque:'Nintendo' },
        { nom:'Rumble Pak N64',                     console:'Nintendo 64',      marque:'Nintendo' },
        { nom:'Controller Pak N64',                 console:'Nintendo 64',      marque:'Nintendo' },
        { nom:'Clavier',                            console:'',                 marque:'' },
        { nom:'Souris',                             console:'',                 marque:'' },
    ],
    autre: [
        { nom:'Dock / Station',                     console:'',     notes:'' },
        { nom:'Support / Stand',                    console:'',     notes:'' },
        { nom:'Chargeur',                           console:'',     notes:'' },
        { nom:'Casque audio',                       console:'',     notes:'' },
        { nom:'Skin / Sticker',                     console:'',     notes:'' },
        { nom:'Protection / Housse',                console:'',     notes:'' },
    ],
};
